### PR TITLE
Expect: 100-continue functional tests w/ and w/o response body

### LINKED ISSUE #617: Test 100-continue scenarios
https://github.com/microsoft/reverse-proxy/blob/37ed6a93f3ea54cc412471ca85ac9b3e38aca749/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L182-L186

That code makes an assumption that request bodies are always read, which is likely false in the case of 100-continues. That check is also one of the few places where it would be problematic if a transform replaced the HttpContent object, the Started property wouldn't be available.

This exception should probably be removed.

### PR DESCRIPTION
**Pull request by alnikola**
It adds functional tests for the scenarios listed below.

The first scenario set is based on [this list](https://github.com/microsoft/reverse-proxy/issues/617#issuecomment-852243785), but modified to be compatible with the actual HttpClient behavior.

- A. HTTP/1.1 POST with a Content-Length is proxied over HTTP/1.1, destination responds with a 100 Continue, the proxy responds with a 100 Continue, the data is uploaded, there's a 200 response.
- B. HTTP/1.1 POST with a Transfer-Encoding is proxied over HTTP/1.1, destination responds with a 100 Continue, the proxy responds with a 100 Continue, the data is uploaded, there's a 200 response.
- C. A & B proxied over HTTP/2
- D. HTTP/1.1 POST with a Content-Length is proxied over HTTP/1.1, destination responds with a 4xx, the data is not uploaded.
- E. D but with Transfer-Encoding.
- F. HTTP/1.1 POST with a Content-Length is proxied over HTTP/2, destination responds with a 4xx and a RESET, the data is not uploaded.
- G. HTTP/2 POST with a Content-Length is proxied over HTTP/2, destination responds with a 4xx and a RESET, the proxy app sends the 4xx and a RESET to cancel the body.

The second scenario set verifies handling of response payload in the cases of successful and terminated responses.

Fixes #617

### CODE REVIEW

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+                }
+            });
+        }
+
+        [Theory]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, false, false)]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, false, true)]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, true, false)]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, true, true)]
+        public async Task PostExpect100_ResponseWithPayload(HttpProtocols proxyProtocol, HttpProtocols destProtocol, bool useContentLength, bool cancelResponse)
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:110]: Why not use the same matrix as the other test, is there something special about HTTP/1 here?

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs [hunk 2]
```diff
@@ -0,0 +1,251 @@
...
+                    context.Response.StatusCode = 200;
+
+                    var responseBody = Encoding.UTF8.GetBytes(contentString + "Response");
+                    if (useContentLength)
+                    {
+                        context.Response.Headers.ContentLength = responseBody.Length;
+                    }
+
+                    var cts = cancelResponse ? new CancellationTokenSource(1) : new CancellationTokenSource();
+                    await context.Response.Body.WriteAsync(responseBody.AsMemory(), cts.Token);
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:129]:
```suggestion
                    if (cancelResponse)
                    {
                        context.Abort();
                    }
                    else
                    {
                        await context.Response.Body.WriteAsync(responseBody.AsMemory());
                    }
```

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs [hunk 3]
```diff
@@ -0,0 +1,251 @@
...
+
+                if (responseAction != null)
+                {
+                    await responseAction(response);
+                }
+            }
+            else
+            {
+                var exception = await Assert.ThrowsAsync<HttpRequestException>(() => client.SendAsync(message));
+                Assert.Equal(typeof(IOException), exception.InnerException.GetType());
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:238]:
```suggestion
                Assert.IsType<IOException>(exception.InnerException);
```

Comment (Tratcher) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:238]: Also check `Assert.Equal(0, contentStream.Position);` in this scenario.

Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:238]: Sorry, I didn't get it. Here, it checks if the **request** content has been read by server which is true even if the **response** is cancelled. Could it be that you actually meant `Assert.Equal(content.Length, contentStream.Position);`?

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs [hunk 4]
```diff
@@ -0,0 +1,251 @@
...
+                    {
+                        // 100 response code is sent automatically on reading Body.
+                        await ReadContent(context, bodyTcs, Encoding.UTF8.GetByteCount(contentString));
+                    }
+
+                    context.Response.StatusCode = destResponseCode;
+                },
+                proxyBuilder => {
+                    proxyBuilder.Services.RemoveAll(typeof(IForwarderHttpClientFactory));
+                    proxyBuilder.Services.TryAddSingleton<IForwarderHttpClientFactory, TestForwarderHttpClientFactory>();
```
[the remark this answers is not in the document]
Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs]: Fixed

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs [hunk 5]
```diff
@@ -0,0 +1,251 @@
...
+        [Theory]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, true, 200)]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, false, 200)]
+        [InlineData(HttpProtocols.Http2, HttpProtocols.Http2, true, 200)]
+        [InlineData(HttpProtocols.Http2, HttpProtocols.Http2, false, 200)]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, true, 400)]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http1, false, 400)]
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http2, true, 400)]
+        [InlineData(HttpProtocols.Http2, HttpProtocols.Http2, true, 400)]
+        public async Task PostExpect100_BodyAlwaysUploaded(HttpProtocols proxyProtocol, HttpProtocols destProtocol, bool useContentLength, int destResponseCode)
```
[the remark this answers is not in the document]
Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs]: I forgot to rename it to match the actual HttpClient behavior. Fixed.

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs (hunk 1 above)
Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:118]: It was a typo. Fixed.

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs [hunk 6]
```diff
@@ -0,0 +1,266 @@
...
+        {
+            var requestBodyTcs = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);
+
+            var contentString = new string('a', 1024 * 1024 * 10);
+            var test = new TestEnvironment(
+                async context =>
+                {
+                    await ReadContent(context, requestBodyTcs, Encoding.UTF8.GetByteCount(contentString));
+
+                    context.Response.StatusCode = 200;
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:128]: You're missing the 4XX scenarios from the other test where we don't expect the request body to be sent? Since we're mainly concerned about the 4XX scenario breaking, you don't need to test the full matrix for the 200 scenario.

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs (hunk 3 above)
Comment (Tratcher) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:252]: Nevermind, I misread this test.

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs (hunk 6 above)
Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:128]: This test verifies cancellation of a response stream by the server. It checks only 200 responses because for 400 responses the server terminates H/2 connection before the response content is sent.

Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:128]: These new tests verify [this cancellation handling logic](https://github.com/dotnet/runtime/issues/53914#issuecomment-857983829) explained by @geoffkizer on dotnet/runtime#53914 discussion

Comment (Tratcher) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:128]: > It checks only 200 responses because for 400 responses the server terminates H/2 connection before the response content is sent.

? 200 and 400 response bodies are treated the same by the server. Nor does a manual 400 response cause an HTTP/2 connection closure.

Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:128]: Hmm, that's interesting. When I ran the [previous test version](https://github.com/microsoft/reverse-proxy/blob/c67c25b7b14165d0c3b406b71e6145238dca86fc/test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs) (first commit in the branch), I was getting exceptions on the `SendAsync` call for the 2 following configurations with 400 response
1.  proxyProtocol: Http1, destProtocol: Http2, useContentLength: True, hasResponseBody: True, destResponseCode: 400
```
System.Net.Http.HttpRequestException : Error while copying content to a stream.
    ---- System.IO.IOException : The response ended prematurely.
```
2. proxyProtocol: Http2, destProtocol: Http2, useContentLength: True, hasResponseBody: True, destResponseCode: 400
```
System.Net.Http.HttpRequestException : Error while copying content to a stream.
    ---- System.IO.IOException : The request was aborted.
    -------- System.Net.Http.Http2StreamException : The HTTP/2 server reset the stream. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
```
Both of the above use H/2 from proxy to destination, thus I assumed it's by design which seems wrong now.

Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs]: I switched the full matrix to use 400 code and kept only 3 cases for 200.

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs [hunk 7]
```diff
@@ -0,0 +1,269 @@
...
+        [InlineData(HttpProtocols.Http1, HttpProtocols.Http2, true, true, 400)]
+        public async Task PostExpect100_ResponseWithPayload(HttpProtocols proxyProtocol, HttpProtocols destProtocol, bool useContentLength, bool cancelResponse, int responseCode)
+        {
+            var requestBodyTcs = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);
+
+            var contentString = new string('a', 1024 * 1024 * 10);
+            var test = new TestEnvironment(
+                async context =>
+                {
+                    await ReadContent(context, requestBodyTcs, Encoding.UTF8.GetByteCount(contentString));
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:129]: Don't you want ReadContent to be conditional on StatusCode like the other test?

**Review by Tratcher — APPROVED** [review]

File: test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs (hunk 7 above)
Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:129]: I don't think an extra `if` is necessary here because this test verifies how the response is processed not the request.

Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:129]: Actually, when I tried adding `if` here like below
```C#
if (responseCode == 200)
{
    await ReadContent(context, requestBodyTcs, Encoding.UTF8.GetByteCount(contentString));
}
```
I started getting the same exceptions as mentioned [above](https://github.com/microsoft/reverse-proxy/pull/1185#discussion_r692872324). I'm not sure if it's by design or bug. Do you know anything about this?

Comment (Tratcher) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:129]: That looks like a product bug. It should be possible for the client to receive a 4XX response including body without uploading the request body.

Please re-open and investigate.

Comment (alnikola) [reply test/ReverseProxy.FunctionalTests/Expect100ContinueTests.cs:129]: I submitted a separate issue for this potential bug #1200
