### PR TITLE
Mitigation of wrong cookie value separator

### LINKED ISSUE #437: [Question/Bug] Cookie value separator changed to comma?
It's more a question, since I can't readily reproduce it:

I'm proxying a basic GET request to a different server (in this case Tomcat) and once in awhile I get a log message in tomcat that an invalid cookie was received (org.apache.tomcat.util.http.parser.Cookie logInvalidHeader). This once in awhile happens if multiple cookies are in one header.
These cookie values should be delimited via semicolon (according to RFC 6265), older RFCs had it as comma. Tomcat's default cookie parser does not accept cookies delimited by comma.

## Wiresharek dump

If I attach wireshark to the listening port, the received plaintext body is (from a test installation)
```ini
GET /test/?url=e508a3ba052148508d707682da9da951&locale=en HTTP/1.1
Host: localhost:61440
Accept: text/html, application/xhtml+xml, application/xml; q=0.9, image/avif, image/webp, image/apng, */*; q=0.8, application/signed-exchange; v=b3; q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE, de; q=0.9, en-US; q=0.8, en; q=0.7
Cookie: access_token=2F1766A645002D0EFBA7E1924594174C3A550598EA5D4B3C3114C6674BE02542, test_data_e508a3ba052148508d707682da9da951=%7B%22id%22%3A%22CASdG2aURvjsWtHNWedyZsvRYPJnK15R2-NRsR1nOibZPQ%22%2C%22title%22%3A%221.2%20cover%22%2C%22url%22%3A%22https%3A%2F%2Flocalhost%3A44302%2Fapi%2FFile%2FASCF-3JBQErG_it4xRT-rbf_BKXVajYvYhsrvXcaUQeadg%2FContent%22%2C%22sequenceNumber%22%3A%220001%22%7D
Referer: https://localhost:44302/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Upgrade-Insecure-Requests: 1
sec-fetch-site: same-origin
sec-fetch-mode: navigate
sec-fetch-dest: iframe
X-Forwarded-Proto: https
X-Forwarded-Host: localhost:44302
X-Forwarded-For: ::1
```
You see the comma separated cookie header values which are wrong.
Funny thing is, as soon as I e.g. attach Fiddler it appears that the cookie separator is still a semicolon, I don't know why ;)

The original request to Kestrel is HTTP2 and the Tomcat is HTTP/1.1  tough.

The best idea I currently have is that something is parsing the Header and reassembling it instead of a verbatim copy, as the Cookie Header is one of the few headers which require semicolon as the separator and things like ``StringValues.ToString()`` is using comma as an separator.
You can reproduce that behaviour with something like this:
```csharp
var output = new HttpClient();
var message = new HttpRequestMessage(HttpMethod.Get, "http://localhost:45844");
message.Headers.Add(HeaderNames.Cookie, new string[]
{
    "test1=1", "test2=2"
});
await output.SendAsync(message);
```
and the headers sent over the wire are comma-separated and not semicolon-separated, that's why my best guess is something is parsing the header value and reassembling it, but I couldn't find any code which would do that and the Transforms Property in the ProxyRoute is null and SessionAffinity is also null (I suspected the CookieSessionAffinity logic).

## Configuration
The configuration is done via code, via the InMemoryConfiguration code from the docs:
```csharp
var routes = new[]
{
    new ProxyRoute()
    {
        RouteId = "proxyRoute",
        ClusterId = "Rewrite",
        Match =
        {
            Path = "/test"
        }
    }
};
var clusters = new[]
{
    new Cluster()
    {
        Id = "Rewrite",
        Destinations =
        {
            {"destination", new Destination() {Address = "http://localhost:61440"}}
        }
    }
};
```
### Further technical details

- Version: 1.0.0-preview.5.20467.3
- Windows 10
- NET Core 3.1.8

### PR DESCRIPTION
**Pull request by ManickaP**
`HttpClient` wrongly uses comma (`,`) as a separator for cookie header values: https://github.com/dotnet/runtime/issues/42856. As well as Kestrel probably doesn't merge cookie header frames for HTTP/2: https://github.com/dotnet/aspnetcore/issues/26461.

This PR mitigates this by collecting all cookie headers while copying them. And concatenating them manually with semi-colon (`;`) before adding it as a single header to the destination request.

Fixes #437

### CODE REVIEW

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+                string statusLine = null;
+                while ((line = await reader.ReadLineAsync()) != null)
+                {
+                    statusLine ??= line;
+                }
+
+                Assert.Equal($"HTTP/1.1 200 OK", statusLine);
+            }
+
+#if NET5_0
```
Comment (ManickaP) [inline test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:58]: I'd love to test HTTP/2 on .NET Core 3.1, but I don't know how to properly set up proxy with TLS. And I don't want to force "enableUnencryptydHttp2" switch...

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+            // HttpClient for H/2 will use different header frames for cookies from a container and from message headers.
+            static async Task ProcessHttp20Request(Uri proxyUri, (string Key, string Value)[] cookies)
+            {
+                // It will first send message header cookie and than the container one thus swap the cookie order to get the order we expect.
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:62]: This relies on really specific behaviors of HttpClient that we expect to change. At least assert the format of the incoming cookie header in a proxy middleware to make sure it meets our expectations. When we fix the issues in HttpClient and Kestrel we'll want to know we can remove the workaround.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+            using var proxyHost = CreateReverseProxyHost(httpProtocol, destinationHostUrl);
+            await proxyHost.StartAsync();
+            var proxyHostUri = new Uri(proxyHost.GetAddress());
+
+            await processRequest(proxyHostUri, cookies);
+
+            Assert.True(tcs.Task.IsCompleted);
+            var cookieHeaders = await tcs.Task;
+            var cookie = Assert.Single(cookieHeaders);
+            Assert.Equal(String.Join("; ", cookies.Select(c => $"{c.Key}={c.Value}")), cookie);
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:111]:
```suggestion
            Assert.Equal("testA=A_Cookie; testB=B_Cookie", cookie);
```

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+        public async Task ProxyAsync_RequestWithCookieHeaders(HttpProtocols httpProtocol, Func<Uri, (string Key, string Value)[], Task> processRequest)
+        {
+            var cookies = new (string Key, string Value)[] { ("testA", "A_Cookie"), ("testB", "B_Cookie") };
+
+            var tcs = new TaskCompletionSource<StringValues>();
+
+            using var destinationHost = CreateDestinationHost(
+                context =>
+                {
+                    if (context.Request.Headers.TryGetValue("Cookie", out var cookieHeaders))
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:88]:
```suggestion
                    if (context.Request.Headers.TryGetValue(HeaderNames.Cookie, out var cookieHeaders))
```

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+            await destinationHost.StopAsync();
+            await proxyHost.StopAsync();
+        }
+
+        private IHost CreateReverseProxyHost(HttpProtocols httpProtocols, string destinationHostUrl)
+        {
+            return CreateHost(httpProtocols,
+                services =>
+                {
+                    services.AddRouting();
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:122]: You won't need this after my PR, I'm adding it by default.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 6]
```diff
@@ -0,0 +1,184 @@
...
+            {
+                using var client = new TcpClient(proxyUri.Host, proxyUri.Port);
+                using var stream = client.GetStream();
+                using var writer = new StreamWriter(stream, Encoding.ASCII);
+                using var reader = new StreamReader(stream, Encoding.ASCII);
+
+                await writer.WriteAsync($"GET / HTTP/1.1\r\n");
+                await writer.WriteAsync($"Host: {proxyUri.Authority}\r\n");
+                await writer.WriteAsync($"Cookie: {cookies[0].Key}={cookies[0].Value}\r\n");
+                await writer.WriteAsync($"Cookie: {cookies[1].Key}={cookies[1].Value}\r\n");
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:43]: Do we need to test this combination? We know it's invalid according to the spec and we don't have reports of people breaking it like this.

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs [hunk 7]
```diff
@@ -622,6 +622,46 @@ public async Task ProxyAsync_RequetsWithBodies_HasHttpContent(string method, str
             Assert.Equal(StatusCodes.Status200OK, httpContext.Response.StatusCode);
         }
 
+        [Theory]
+        [InlineData("HTTP/1.1")]
+        [InlineData("HTTP/2")]
```
Comment (Tratcher) [inline test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs:627]: Protocol isn't relevant to this test behavior.

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs [hunk 8]
```diff
@@ -622,6 +622,46 @@ public async Task ProxyAsync_RequetsWithBodies_HasHttpContent(string method, str
...
+        public async Task ProxyAsync_RequestWithCookieHeaders(string protocol)
+        {
+            var cookies = new [] { "testA=A_Cookie", "testB=B_Cookie", "testC=C_Cookie" };
+            var httpContext = new DefaultHttpContext();
+            httpContext.Request.Method = "GET";
+            httpContext.Request.Protocol = protocol;
+            httpContext.Request.Headers.Add("Cookie", cookies.Take(2).ToArray());
+            httpContext.Request.Headers.Append("Cookie", cookies.Last());
```
Comment (Tratcher) [inline test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs:635]: Append aggregates into a single StringValues, this is the same as calling:
```suggestion
            httpContext.Request.Headers.Add("Cookie", cookies);
```

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs [hunk 9]
```diff
@@ -622,6 +622,46 @@ public async Task ProxyAsync_RequetsWithBodies_HasHttpContent(string method, str
             Assert.Equal(StatusCodes.Status200OK, httpContext.Response.StatusCode);
         }
 
+        [Theory]
+        [InlineData("HTTP/1.1")]
+        [InlineData("HTTP/2")]
+        public async Task ProxyAsync_RequestWithCookieHeaders(string protocol)
+        {
+            var cookies = new [] { "testA=A_Cookie", "testB=B_Cookie", "testC=C_Cookie" };
```
Comment (Tratcher) [inline test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs:630]:
```suggestion
            // This is an invalid format per spec but may happen due to https://github.com/dotnet/aspnetcore/issues/26461
            var cookies = new [] { "testA=A_Cookie", "testB=B_Cookie", "testC=C_Cookie" };
```

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs [hunk 10]
```diff
@@ -622,6 +622,46 @@ public async Task ProxyAsync_RequetsWithBodies_HasHttpContent(string method, str
...
+            var client = MockHttpHandler.CreateClient(
+                (HttpRequestMessage request, CancellationToken cancellationToken) =>
+                {
+                    Assert.Equal(new Version(2, 0), request.Version);
+                    Assert.Equal("GET", request.Method.Method, StringComparer.OrdinalIgnoreCase);
+                    Assert.Null(request.Content);
+                    Assert.True(request.Headers.TryGetValues("Cookie", out var cookieHeaders));
+                    Assert.NotNull(cookieHeaders);
+                    var cookie = Assert.Single(cookieHeaders);
+                    Assert.Equal(String.Join("; ", cookies), cookie);
```
Comment (Tratcher) [inline test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs:648]:
```suggestion
                    Assert.Equal("testA=A_Cookie; testB=B_Cookie; testC=C_Cookie", cookie);
```

**Review by Tratcher — COMMENTED** [review]
Looks like a good start. Most of my comments are about simplifying the logic and tests.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs (hunk 6 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:43]: That means that we don't need to test HTTP 1.1 case at all.

Multiple cookies in a single header must be concatenated by ';' (according to spec.) and even if they're not (e.g. `HttpClient`), we decided **not** to handle this particular case.

Comment (Tratcher) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs:43]: You could include a HTTP/1.1 test that sends a properly formatted cookie header just to make sure we don't break it with the workaround. Optional..

File: src/ReverseProxy/Service/Proxy/HttpProxy.cs [hunk 11]
```diff
@@ -379,13 +379,18 @@ private static void CopyRequestHeaders(HttpContext context, HttpRequestMessage d
         {
             // Transforms that were run in the first pass.
             HashSet<string> transformsRun = null;
+
+            // HttpClient wrongly uses comma (",") instead of semi-colon (";") as a separator for Cookie headers.
+            // To mitigate this, we collect them, concatenate them manually and put them back as a single header value.
+            List<string> cookies = null;
```
[the remark this answers is not in the document]
Comment (ManickaP) [reply src/ReverseProxy/Service/Proxy/HttpProxy.cs]: Done.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 12]
```diff
@@ -0,0 +1,184 @@
...
+
+namespace Microsoft.ReverseProxy
+{
+    public class HttpProxyTests
+    {
+        public static IEnumerable<object[]> RequestWithCookieHeadersTestData()
+        {
+            yield return new object[] { HttpProtocols.Http1, (Func<Uri, (string Key, string Value)[], Task>)ProcessHttp11Request };
+#if NET5_0
+            yield return new object[] { HttpProtocols.Http2, (Func<Uri, (string Key, string Value)[], Task>)ProcessHttp20Request };
```
[the remark this answers is not in the document]
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs]: The tests split into 2 classes, one per protocol.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs [hunk 13]
```diff
@@ -0,0 +1,184 @@
...
+                var client = new HttpClient(handler);
+                var message = new HttpRequestMessage(HttpMethod.Get, proxyUri);
+                message.Version = HttpVersion.Version20;
+                message.VersionPolicy = HttpVersionPolicy.RequestVersionExact;
+
+                message.Headers.Add("Cookie", $"{cookies[0].Key}={cookies[0].Value}");
+                using var response = await client.SendAsync(message);
+                response.EnsureSuccessStatusCode();
+            }
+#endif
```
[the remark this answers is not in the document]
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs]: Done.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs (hunk 2 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs]: Added `CheckCookieHeaderMiddleware`.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs (hunk 3 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs]: Replaced with `expectedCookieString` with a comment.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs (hunk 4 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs]: Replaced all occurrences.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs (hunk 5 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs]: Removed.

File: test/ReverseProxy.FunctionalTests/HttpProxyTests.cs (hunk 6 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyTests.cs]: HTTP1.1 test left with proper cookie header.

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs (hunk 7 above)
Comment (ManickaP) [reply test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs]: Removed.

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs (hunk 8 above)
Comment (ManickaP) [reply test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs]: Done.

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs (hunk 9 above)
Comment (ManickaP) [reply test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs:629]: Done.

File: test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs (hunk 10 above)
Comment (ManickaP) [reply test/ReverseProxy.Tests/Service/Proxy/HttpProxyTests.cs]: Replaced with `expectedCookieString` with a comment.

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs [hunk 14]
```diff
@@ -0,0 +1,214 @@
...
+            {
+                _next = next;
+            }
+
+            public async Task Invoke(HttpContext context)
+            {
+                // Ensure that CookieA is the first and CookieB the last.
+                Assert.True(context.Request.Headers.TryGetValue(HeaderNames.Cookie, out var headerValues));
+                Assert.StartsWith(CookieA, headerValues);
+                Assert.EndsWith(CookieB, headerValues);
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:153]: Careful what you're asserting here, you're expecting different results for HTTP/1 and HTTP/2.

`headerValues` is a StringValues, but you're passing it to StartsWith which takes a string. There's an implicit converter from StringValues to string which concatenates with commas (just like the original bug). Rather than using StartsWith, you want to check the count and value of each StringValues entry to make sure it's what you expect. E.g. Count should be 1 for HTTP/1 and 2 for HTTP/2.

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs [hunk 15]
```diff
@@ -0,0 +1,214 @@
...
+
+                await _next.Invoke(context);
+            }
+        }
+    }
+    public class HttpProxyCookieTests_Http1 : HttpProxyCookieTests
+    {
+        public override HttpProtocols HttpProtocol => HttpProtocols.Http1;
+
+        // Using simple TcpClient since HttpClient will always concatenate cookies with comma separator.
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:163]: Since you're not testing multi-header cookies for HTTP/1 you could revert back to the standard HttpClient.

**Review by Tratcher — COMMENTED** [review]
The fix looks good. Some minor comments left on the tests.

File: src/ReverseProxy/Service/Proxy/HttpProxy.cs [hunk 16]
```diff
@@ -430,6 +430,13 @@ private static void CopyRequestHeaders(HttpContext context, HttpRequestMessage d
             // as long as they appear in one (and only one, otherwise they would be duplicated).
             static void AddHeader(HttpRequestMessage request, string headerName, StringValues value)
             {
+                // HttpClient wrongly uses comma (",") instead of semi-colon (";") as a separator for Cookie headers.
+                // To mitigate this, we concatenate them manually and put them back as a single header value.            
+                if (headerName == HeaderNames.Cookie && value.Count > 1)
```
[the remark this answers is not in the document]
Comment (ManickaP) [reply src/ReverseProxy/Service/Proxy/HttpProxy.cs]: Fixed.

File: src/ReverseProxy/Service/Proxy/HttpProxy.cs [hunk 17]
```diff
@@ -430,6 +430,13 @@ private static void CopyRequestHeaders(HttpContext context, HttpRequestMessage d
             // as long as they appear in one (and only one, otherwise they would be duplicated).
             static void AddHeader(HttpRequestMessage request, string headerName, StringValues value)
             {
+                // HttpClient wrongly uses comma (",") instead of semi-colon (";") as a separator for Cookie headers.
+                // To mitigate this, we concatenate them manually and put them back as a single header value.
```
[the remark this answers is not in the document]
Comment (ManickaP) [reply src/ReverseProxy/Service/Proxy/HttpProxy.cs]: Fixed.

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs [hunk 18]
```diff
@@ -0,0 +1,214 @@
...
+        public static readonly string CookieB = $"{CookieBKey}={CookieBValue}";
+        public static readonly string Cookies = $"{CookieA}; {CookieB}";
+
+        public abstract HttpProtocols HttpProtocol { get; }
+        public abstract Task ProcessHttpRequest(Uri proxyHostUri);
+
+        [Fact]
+        public async Task ProxyAsync_RequestWithCookieHeaders()
+        {
+            var tcs = new TaskCompletionSource<StringValues>();
```
[the remark this answers is not in the document]
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs]: Fixed.

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs [hunk 19]
```diff
@@ -0,0 +1,214 @@
...
+                // Ensure that CookieA is the first and CookieB the last.
+                Assert.True(context.Request.Headers.TryGetValue(HeaderNames.Cookie, out var headerValues));
+                Assert.StartsWith(CookieA, headerValues);
+                Assert.EndsWith(CookieB, headerValues);
+
+                await _next.Invoke(context);
+            }
+        }
+    }
+    public class HttpProxyCookieTests_Http1 : HttpProxyCookieTests
```
[the remark this answers is not in the document]
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs]: Fixed.

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs (hunk 14 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs]: Added different set of asserts per `context.Request.Protocol`.

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs (hunk 15 above)
Comment (ManickaP) [reply test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:178]: Done.

File: src/ReverseProxy/Service/Proxy/HttpProxy.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (Tratcher) [reply src/ReverseProxy/Service/Proxy/HttpProxy.cs]: I don't see this change in your PR?

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs [hunk 20]
```diff
@@ -0,0 +1,214 @@
...
+                await _next.Invoke(context);
+            }
+        }
+    }
+
+    public class HttpProxyCookieTests_Http1 : HttpProxyCookieTests
+    {
+        public override HttpProtocols HttpProtocol => HttpProtocols.Http1;
+
+        // Using simple TcpClient since HttpClient will always concatenate cookies with comma separator.
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:178]:
```suggestion
```

File: test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs [hunk 21]
```diff
@@ -0,0 +1,214 @@
...
+        public override async Task ProcessHttpRequest(Uri proxyHostUri)
+        {
+            using var client = new HttpClient();            
+            using var message = new HttpRequestMessage(HttpMethod.Get, proxyHostUri);
+            message.Headers.Add(HeaderNames.Cookie, $"{Cookies}");
```
Comment (Tratcher) [inline test/ReverseProxy.FunctionalTests/HttpProxyCookieTests.cs:183]:
```suggestion
            message.Headers.Add(HeaderNames.Cookie, Cookies);
```

File: src/ReverseProxy/Service/Proxy/HttpProxy.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (ManickaP) [reply src/ReverseProxy/Service/Proxy/HttpProxy.cs]: Sorry, my bad, should be there now.

**Review by Tratcher — APPROVED** [review]
