### PR TITLE
Passive health policy controlling request transport failures rate in proxying them to destinations

### LINKED ISSUE #498: Transport failure rate passive health check policy
Implement a passive health check policy marking a destination as unhealthy when a percentage of failed requests in the specified time period exceeded the given limit. Initially, it implemented as `TransportFailureRateHealthPolicy` in #459, but then was moved out of the scope.

### PR DESCRIPTION
**Pull request by alnikola**
`TransportFailureRateHealthPolicy` calculates the proxied requests failure rate for each destination and marks it as unhealthy if the specified limit is exceeded.

Fixes #498

### CODE REVIEW

**Comment by alnikola** [comment]
@davidfowl @Tratcher This is a follow-up PR for a passive `TransportFailureRateHealthPolicy` descoped from #459.

**Comment by alnikola** [comment]
Oops. I accidentally pushed a rebuilt documentation.

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs [hunk 1]
```diff
@@ -0,0 +1,152 @@
...
+            UpdateDestinationHealth(cluster.Config, destination, newHealth);
+        }
+
+        private DestinationHealth EvaluateProxiedRequest(ClusterInfo cluster, DestinationInfo destination, bool failed)
+        {
+            var history = _requestHistories.GetOrCreateValue(destination);
+            var metadataName = TransportFailureRateHealthPolicyOptions.FailureRateLimitMetadataName;
+            var rateLimitEntry = _clusterFailureRateLimits.GetValue(cluster, c => new ParsedMetadataEntry<double>(TryParse, c, TransportFailureRateHealthPolicyOptions.FailureRateLimitMetadataName));
+            var rateLimit = rateLimitEntry.GetParsedOrDefault(_policyOptions.DefaultFailureRateLimit);
+            lock (history)
```
Comment (davidfowl) [inline src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:58]: This will be a bottleneck.

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+        {
+            var error = context.Features.Get<IProxyErrorFeature>();
+            var newHealth = EvaluateProxiedRequest(cluster, destination, error != null);
+            UpdateDestinationHealth(cluster.Config, destination, newHealth);
+        }
+
+        private DestinationHealth EvaluateProxiedRequest(ClusterInfo cluster, DestinationInfo destination, bool failed)
+        {
+            var history = _requestHistories.GetOrCreateValue(destination);
+            var metadataName = TransportFailureRateHealthPolicyOptions.FailureRateLimitMetadataName;
```
Comment (davidfowl) [inline src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:55]: This is unused.

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+                return failureRate < rateLimit ? DestinationHealth.Healthy : DestinationHealth.Unhealthy;
+            }
+        }
+
+        private void UpdateDestinationHealth(ClusterConfig cluster, DestinationInfo destination, DestinationHealth newPassiveHealth)
+        {
+            var state = destination.DynamicState;
+            if (newPassiveHealth != state.Health.Passive)
+            {
+                destination.DynamicState = new DestinationDynamicState(state.Health.ChangePassive(newPassiveHealth));
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:74]: This is where we need to be concerned about triggering signal updates synchronously from a request thread. This can cause a sync, locked, rebuild of the healthy destinations list, right?

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs (hunk 1 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:57]: I believe I can implement a lock-free algorithm here, but first let's agree on whether or not we are satisfied with how Signal is used because depending on that discussion outcome this whole policy can require substantial changes.

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs (hunk 3 above)
Comment (davidfowl) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:73]: Right, this is exactly what I'm worried about.

Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:73]: I do agree that the concerns are valid, but would also like to dig into the details the code flow.

1. Normally, assigning `Unhealthy` to `destination.DynamicState.Health.Passive` will happen only once in a reactivation period (scale of minutes) for each destination because right after setting `Unhealthy` the destination gets excluded from consideration by next requests.
2. It's correct that `ClusterInfo.DynamicState.HealthyDestinations` can get rebuilt synchronously here, but under normal conditions it shouldn't happen frequently for the same cluster. In extreme cases, where most of cluster's destinations getting unhealthy, we should probably anyways enable "panic" mode where `HealthyDestinations` rebuilding will be suspended.

P.S. I will file an issue for "panic" cluster's health mode.

Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:73]: All in all, I would firstly address locking-related concerns (e.g. possibility of a deadlock), and only then performance-related ones.

Comment (Tratcher) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:73]: It might be better to kick this out to a service similar to the reactivation scheduler, one that could A) move the rebuild off of the request thread, and B) debounce some of the changes, e.g. if many requests to a destination fail in close proximity, you don't want to update the state many times. We might be able to build both of those capabilities into Signals directly.

Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:73]: >B) debounce some of the changes, e.g. if many requests to a destination fail in close proximity

It's kind of already done by this if clause `if (newPassiveHealth != state.Health.Passive)` that prevents consecutive updates of the same destination. Meaning, once it got unhealthy, its health won't be updated till a reactivation.

Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:73]: Though, it costs one Signal read per request.

Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:73]: I found an existing issue for panic mode #83.

Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs]: I implemented IDestinationHealthUpdater applying changes to active and passive destination health properties asynchronously as well as handling bulk updates in a thread-safe way. Later, it can also implement the panic mode feature. Please, check it out.

File: src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs [hunk 4]
```diff
@@ -19,51 +19,36 @@ internal class ConsecutiveFailuresHealthPolicy : IActiveHealthCheckPolicy
...
             {
-                cluster.ResumeHealthyDestinationUpdates();
+                var destination = probingResults[i].Destination;
+
+                var count = _failureCounters.GetOrCreateValue(destination);
+                var newHealth = EvaluateHealthState(threshold, probingResults[i].Response, count);
+                newHealthPairs[i] = (destination, newHealth);
             }
+
+            _ = _healthUpdater.SetActiveAsync(cluster, newHealthPairs);
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs:51]: @davidfowl was your original concern here that health probes could be running in parallel, or that the updates were happening in parallel?

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+            var updateSyncToken = new object();
+            if (!_activeSynchTokens.TryAdd(cluster, updateSyncToken))
+            {
+                // Don't allow concurrent updates.
+                return Task.CompletedTask;
+            }
+
+            return Task.Run(() =>
+            {
+                if (!_activeSynchTokens.TryGetValue(cluster, out var currentToken))
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:36]: I don't see how you could get into this state? The only remove happens at the end of this method, there is no cancel.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+
+        public DestinationHealthUpdater(IReactivationScheduler reactivationScheduler, ILogger<DestinationHealthUpdater> logger)
+        {
+            _reactivationScheduler = reactivationScheduler ?? throw new ArgumentNullException(nameof(reactivationScheduler));
+            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
+        }
+
+        public Task SetActiveAsync(ClusterInfo cluster, IEnumerable<(DestinationInfo Destination, DestinationHealth NewHealth)> newHealthPairs)
+        {
+            var updateSyncToken = new object();
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:27]: The value isn't used for anything, it could be static, or null, or the cluster itself?

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+                {
+                    cluster.ResumeHealthyDestinationUpdates();
+                    _activeSynchTokens.TryRemove(cluster, out _);
+                }
+            });
+        }
+
+        public Task SetPassiveAsync(ClusterInfo cluster, DestinationInfo destination, DestinationHealth newHealth, TimeSpan reactivationPeriod)
+        {
+            return Task.Run(() =>
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:77]: Can we do this without a closure? It's going to be pretty common.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+
+namespace Microsoft.ReverseProxy.Service.HealthChecks
+{
+    internal class DestinationHealthUpdater : IDestinationHealthUpdater
+    {
+        private readonly IReactivationScheduler _reactivationScheduler;
+        private readonly ILogger<DestinationHealthUpdater> _logger;
+        private readonly ConcurrentDictionary<ClusterInfo, object> _activeSynchTokens = new ConcurrentDictionary<ClusterInfo, object>();
+
+        public DestinationHealthUpdater(IReactivationScheduler reactivationScheduler, ILogger<DestinationHealthUpdater> logger)
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:19]: The IReactivationScheduler could be absorbed by DestinationHealthUpdater, it's the only caller right now right?

File: src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs (hunk 4 above)
Comment (davidfowl) [reply src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs:51]: Updates triggered from the request.

File: src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+using System.Threading.Tasks;
+using Microsoft.ReverseProxy.RuntimeModel;
+
+namespace Microsoft.ReverseProxy.Service.HealthChecks
+{
+    /// <summary>
+    /// Updates destinations' health states when it's requested by a health check policy
+    /// while taking into account not only the new evaluated value but also the overall current cluster's health state.
+    /// </summary>
+    public interface IDestinationHealthUpdater
```
Comment (davidfowl) [inline src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs:15]: We don't need this. We need to support signals dispatching off the caller's thread.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 6 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs]: It was a leftover from another lock-based approach (token was locked on). Replaced with `null`.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 8 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:19]: In my opinion, they have different responsibilities. `IDestinationHealthUpdater` decides whether or not apply health state changes requested by a policy and actually applies them. The former part (decision making) is not implemented in this PR, but can be added as part of #83.

File: src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs (hunk 9 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs:15]: As far as I see it, the only reliable way to avoid deadlocks or slowing down a request is to do "heavy" Signal updates in background. Do you suggest to fire up a background task right from SignalContext? Or do you have a completely different approach to addressing this issue in mind?

This abstraction also synchronizes concurrent bulk update operations involving Pause/Resume healthy destination collection rebuilding.

Comment (davidfowl) [reply src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs:15]: > Do you suggest to fire up a background task right from SignalContext?

Yes. I think we should do that. Similar to how TaskCompletionSource has RunContinuationsAsynchronously, this is similar. We don't need a new abstraction for this.

Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs:15]: I see. Though, currently signal's value is updated through a simple property setter which cannot be parameterized and I'm not sure whether it's a good idea to always run updates in background. Thus, we might need to introduce a `Signal.SetValueAsync()` method or something similar.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 5 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs]: I was thinking about adding a cancellation logic, but now it seems to soon since we have not yet decided whether this type should exist at all. It's been deleted.

**Comment by alnikola** [comment]
Converting it to a draft until signals removal is completed in #505.

File: src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs (hunk 4 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs]: `SetActive` updates the active health state **synchronously** now.

File: src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs (hunk 9 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs:15]: Signals have been removed.

**Comment by alnikola** [comment]
Remaining work:
0. Address a few currently open comments.
1. Unit tests for DestinationHealthUpdater
2. Decision on debouncing passive health state changes
3. Documentation update taking into account all of the above and the introduced policy itself

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 8 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:18]: Actually, you can be right. `ReactivationScheduler` contains only few lines of production code (besides logging) which can be seen as dealing with health state updates. So, it could make sense to merge the `IReactivationScheduler` into this new `DestinationHealthUpdater`.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+                }
+            }
+
+            if (changed)
+            {
+                cluster.UpdateDynamicState();
+            }
+        }
+
+        public Task SetPassiveAsync(ClusterInfo cluster, DestinationInfo destination, DestinationHealth newHealth, TimeSpan reactivationPeriod)
```
[the remark this answers is not in the document]
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:54]: Previously, @davidfowl advises to return a task and dismiss it in such case.

File: src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+        /// will be reset to <see cref="DestinationHealth.Unknown"/>. Otherwise, it's not used.</param>
+        /// <returns><see cref="Task"/> representing a passive health update operation.</returns>
+        Task SetPassiveAsync(ClusterInfo cluster, DestinationInfo destination, DestinationHealth newHealth, TimeSpan reactivationPeriod);
+
+        /// <summary>
+        /// Sets the active health values on the given destinations.
+        /// </summary>
+        /// <param name="cluster">Cluster.</param>
+        /// <param name="newHealths">New active health values.</param>
+        void SetActive(ClusterInfo cluster, IEnumerable<(DestinationInfo Destination, DestinationHealth NewHealth)> newHealths);
```
[the remark this answers is not in the document]
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs:34]: Got it. I was not sure what is our guidance on this.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 7 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs]: Changed to a closure-less call to `TaskFactory.StartNew`.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 8 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs]: `ReactivationScheduler` is merged into `DestinationHealthUpdater`.

File: src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs (hunk 11 above)
[the remark this answers is not in the document]
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs]: Fixed.

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs (hunk 1 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:61]: Hmm, it seems implementing a lock-free algorithm here requires a untrivial amount of effort. Do you really think it can noticeably hurt perf? It does a little work under the lock which is mainly about updating counters. Actual health state change is done outside.

If it does look like a bottleneck, I'd suggest we address it later in a separate PR. What do you think?

Comment (Tratcher) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:61]: This lock is per destination and destinations are expected to hit thousands of RPS. It's definitely going to cause some contention, but we'll have to measure it to see how much.

Doing the measurements and optimizations in a follow-up item should be OK.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs [hunk 12]
```diff
@@ -0,0 +1,140 @@
...
+        {
+            return Task.Factory.StartNew(s =>
+            {
+                (var c, var d, var h, var p) = ((ClusterInfo, DestinationInfo, DestinationHealth, TimeSpan)) s;
+                var healthState = d.Health;
+                if (h != healthState.Passive)
+                {
+                    healthState.Passive = h;
+                    ScheduleReactivation(c, d, h, p);
+                    c.UpdateDynamicState();
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:65]: UpdateDynamicState is the only part that needs to be in a background task. It would be better to do the health update and reactivation scheduling synchronously, those are quick and time sensitive.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (davidfowl) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:55]: Let me clarify, if this interface is meant to be a fire and forget interface then it's on to return void here *but* the implementation should use a discard _.

If we want to give the caller the option of awaiting then the caller should use the discard.

[the remark this answers is not in the document]
Comment (Tratcher) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:55]: I checked with David and he said it would be OK for this method to be void and to do the discard internally: `_ = Task.Factory.StartNew`. What he wants to avoid is any usage of `async void`.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 12 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs]: Fixed.

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:55]: Discarding the task internally will jeopardize unit testing where currently I can simply call `await`, but without a task, would have to use delays.

**Comment by alnikola** [comment]
@Tratcher @davidfowl I changed `ClusterInfo.UpdateDynamicState` in such a way that only one of multiple concurrent calls takes effect. `ProxyConfigManager` now calls an internal blocking `ForceUpdateDynamicState` that waits till a lock gets free to apply changes.

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs [hunk 13]
```diff
@@ -59,13 +60,38 @@ public ClusterConfig Config
...
+                if (force)
+                {
+                    Monitor.Enter(_stateLock, ref lockTaken);
+                }
+                else
+                {
+                    Monitor.TryEnter(_stateLock, ref lockTaken);
+                }
+
+                if (!lockTaken)
```
Comment (Tratcher) [inline src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:90]: This isn't quite enough, it can cause you to miss updates that happened after the prior rebuild started. We can't rely on ForceUpdateDynamicState being called again in the future, we don't know when that will be. Any call to UpdateDynamicStateInternal needs to guarantee that a fresh rebuild happens, even if one is already in progress. The trick is to only de-duplicate rebuilds that haven't started yet.

Comment (alnikola) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:90]: Yes, that's correct, but I'm not sure if that's a real problem because of the following. If there are several health state updates/rebuilt requests which are so close that they concurrently call this method, I think there is no reliable way to order them by causality chain. How can we be sure that an update made 5ms after another one is actually newer?

Comment (Tratcher) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:90]: I don't think this method cares who triggered which update, it's safer to rebuild when asked. If one update is in progress and four more are requested before it finishes, then at least one more rebuild needs to happen (but not all 4).

Comment (alnikola) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:90]: But why do you think that if in example 1 rebuild gets request at T0 and then at T1 (5ms later) 3 more rebuilts are requested again, we should do 1 + 1 rebuild instead just 1 going on? Could you may be give some specific case that concerns you the most?

Comment (Tratcher) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:90]: The rebuild that's in progress is scanning the list of destinations d1->dN. If the state of d1 changes after it's been scanned then another rebuild is required (as signaled by another call to UpdateDynamicStateInternal). If 3 more rebuilds were requested, we only have to do one full rebuild to ensure we pick up new changes anywhere in the list.

Comment (alnikola) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:90]: Ok, I see the point. It means if we got at least one concurrent rebuild request while the current one is going we have to start it over again. I agree it kind of make sense. Though, I'm a bit afraid that we can see "long recalculation tails" with that approach. But, it's probably unavoidable.

Comment (Tratcher) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:90]: Yeah, we'll never end up doing more builds than requested, but hopefully we can de-duplicate.

The next question is how to track the +1 rebuild. I'd considered looping inside the lock, but that could end up blocking one caller for a long time.

File: docs/docfx/articles/dests-health-checks.md [hunk 14]
```diff
@@ -242,21 +245,80 @@ endpoints.MapReverseProxy(proxyPipeline =>
...
+There are two sets of policy parameters defined globally and on per cluster level.
+
+Global parameters are set via the options mechanism using `TransportFailureRateHealthPolicyOptions` type with the following properties:
+
+- `DetectionWindowSize` - period of time while detected failures are kept and taken into account in the rate calculation. Default is `00:01:00`.
+- `MinimalTotalCountThreshold` - minimal total number of requests which must be proxied to a destination within the detection window before this policy starts evaluating the destination's health and enforcing the failure rate limit. Default is `10`.
+- `DefaultFailureRateLimit` - default failure rate limit for a destination to be marked as unhealhty that is applied if it's not set on a cluster's metadata. The value is in range `(0,1)`. Default is `0.3 (30%)`.
```
Comment (Tratcher) [inline docs/docfx/articles/dests-health-checks.md:256]:
```suggestion
- `DefaultFailureRateLimit` - default failure rate limit for a destination to be marked as unhealthy that is applied if it's not set on a cluster's metadata. The value is in range `(0,1)`. Default is `0.3` (30%).
```

File: docs/docfx/articles/dests-health-checks.md [hunk 15]
```diff
@@ -242,21 +245,80 @@ endpoints.MapReverseProxy(proxyPipeline =>
...
...analyzing responses returned by destinations. For each response from a destination belonging to a cluster with enabled passive health checks, `PassiveHealthCheckMiddleware` invokes an [IPassiveHealthCheckPolicy](xref:Microsoft.ReverseProxy.Service.HealthChecks.IPassiveHealthCheckPolicy) specified for the cluster. The policy analyzes the given response, evaluates a new destination's passive health state and calls [IDestinationHealthUpdater](xref:Microsoft.ReverseProxy.Service.HealthChecks.IDestinationHealthUpdater) to actually update [DestinationHealthState.Passive](xref:Microsoft.ReverseProxy.RuntimeModel.DestinationHealthState.Passive) value. Update happens asynchronously in the background and doesn't block the main pipeline. When a destination gets marked as unhealthy, it stops receiving new requests until it gets reactivated after a configured period. Reactivation means the destination's `DestinationHealthState.Passive` state is reset from `Unhealthy` to `Unknown` and the cluster's list of healthy destinations is rebuilt to include it. A reactivation is scheduled by `IDestinationHealthUpdater` right after setting the destination's `DestinationHealthState.Passive` to `Unhealthy`.
```
Comment (Tratcher) [inline docs/docfx/articles/dests-health-checks.md:273]:
```suggestion
The main component is [PassiveHealthCheckMiddleware](xref:Microsoft.ReverseProxy.Middleware.PassiveHealthCheckMiddleware) sitting in the request pipeline and analyzing responses returned by destinations. For each response from a destination belonging to a cluster with enabled passive health checks, `PassiveHealthCheckMiddleware` invokes an [IPassiveHealthCheckPolicy](xref:Microsoft.ReverseProxy.Service.HealthChecks.IPassiveHealthCheckPolicy) specified for the cluster. The policy analyzes the given response, evaluates a new destination's passive health state and calls [IDestinationHealthUpdater](xref:Microsoft.ReverseProxy.Service.HealthChecks.IDestinationHealthUpdater) to actually update [DestinationHealthState.Passive](xref:Microsoft.ReverseProxy.RuntimeModel.DestinationHealthState.Passive) value. The update happens asynchronously in the background and doesn't block the request pipeline. When a destination gets marked as unhealthy, it stops receiving new requests until it gets reactivated after a configured period. Reactivation means the destination's `DestinationHealthState.Passive` state is reset from `Unhealthy` to `Unknown` and the cluster's list of healthy destinations is rebuilt to include it. A reactivation is scheduled by `IDestinationHealthUpdater` right after setting the destination's `DestinationHealthState.Passive` to `Unhealthy`.
```

File: docs/docfx/articles/dests-health-checks.md [hunk 16]
```diff
@@ -242,21 +245,80 @@ endpoints.MapReverseProxy(proxyPipeline =>
...
-      (schedule a reactivation)
+      IDestinationHealthUpdater --(Asynchronously update passive state)--> DestinationInfo.Health.Passive
                   |
                   V
-        IReactivationScheduler --(set to Unknown)--> DestinationInfo.Health.Passive
+      (Schedule a reactivation) --(Set to Unknown)--> DestinationInfo.Health.Passive
+```
+
+### Extensibility
+There is one main extensibility point in the passive health check subsystem.
```
Comment (Tratcher) [inline docs/docfx/articles/dests-health-checks.md:292]:
```suggestion
There is one main extensibility point in the passive health check subsystem, the `IPassiveHealthCheckPolicy`.
```

File: src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs [hunk 17]
```diff
@@ -0,0 +1,137 @@
...
+        }
+
+        private Task Reactivate(ClusterInfo cluster, DestinationInfo destination)
+        {
+            var healthState = destination.Health;
+            if (healthState.Passive == DestinationHealth.Unhealthy)
+            {
+                healthState.Passive = DestinationHealth.Unknown;
+                cluster.UpdateDynamicState();
+                Log.PassiveDestinationHealthResetToUnkownState(_logger, destination.DestinationId);
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs:88]: Log before continuing with the update, it's non-trivial.
```suggestion
                healthState.Passive = DestinationHealth.Unknown;
                Log.PassiveDestinationHealthResetToUnkownState(_logger, destination.DestinationId);
                cluster.UpdateDynamicState();
```

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs (hunk 13 above)
Comment (alnikola) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs]: Deduplication improved to allow both of the first and the last rebuilds proceed. Check it out.

File: src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs [hunk 18]
```diff
@@ -0,0 +1,36 @@
...
+        /// Asynchronously sets the passive health on the given <paramref name="destination"/>.
+        /// </summary>
+        /// <param name="cluster">Cluster.</param>
+        /// <param name="destination">Destination.</param>
+        /// <param name="newHealth">New passive health value.</param>
+        /// <param name="reactivationPeriod">If <paramref name="newHealth"/> is <see cref="DestinationHealth.Unhealthy"/>,
+        /// this parameter specifies a reactivation period after which the destination's <see cref="DestinationHealthState.Passive"/> value
+        /// will be reset to <see cref="DestinationHealth.Unknown"/>. Otherwise, it's not used.</param>
+        /// <returns><see cref="Task"/> representing a passive health update operation.</returns>
+        Task SetPassiveAsync(ClusterInfo cluster, DestinationInfo destination, DestinationHealth newHealth, TimeSpan reactivationPeriod);
```
Comment (Tratcher) [inline src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs:27]: I'm still not sure how we communicate to developers that a passive health check policy should not wait for this task, it's intended only for tests. We'll need to revisit how we test this so it doesn't leak into the public API.

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs (hunk 1 above)
Comment (Tratcher) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:61]: Have you filed this yet?

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs [hunk 19]
```diff
@@ -59,35 +61,80 @@ public ClusterConfig Config
...
-                        return passive != DestinationHealth.Unhealthy && active != DestinationHealth.Unhealthy;
-                    }).ToList().AsReadOnly();
+                        lockTaken = false;
+                        _updateRequests.Release();
+                    }
+                }
+            }
+            finally
+            {
+                // This releases the semaphore in case of an exception thrown by 'lock' call.
```
Comment (Tratcher) [inline src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:133]: `lock` can throw?

Can't you accomplish the same thing by inverting the `lock` and the inner `try`? I don't see why you need a try/finally both inside and outside the lock.

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs [hunk 20]
```diff
@@ -59,35 +61,80 @@ public ClusterConfig Config
...
+        {
+            UpdateDynamicStateInternal(force: true);
+        }
+
+        private void UpdateDynamicStateInternal(bool force)
         {
             // Prevent overlapping updates. If there are multiple signals that state needs to be updated,
             // we want to ensure that updates don't conflict with each other. E.g. if state changes
             // while an update is already in progress, the next update should wait until the current one finishes
             // to ensure they don't race to set _dynamicState and end up with the stale one overwriting the fresh one.
```
Comment (Tratcher) [inline src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:78]: Update the comment to explain the reason for and the mechanics of the double lock.

**Review by Tratcher — APPROVED** [review]

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs [hunk 21]
```diff
@@ -59,35 +61,80 @@ public ClusterConfig Config
...
-                var allDestinations = DestinationManager.Items;
-                var healthyDestinations = allDestinations;
+                if (force)
+                {
+                    lockTaken = true;
+                    _updateRequests.Wait();
+                }
+                else
+                {
+                    lockTaken = _updateRequests.Wait(0);
```
Comment (halter73) [inline src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:89]: Why use a SemaphoreSlim at all rather than Monitor.TryEnter?

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs [hunk 22]
```diff
@@ -59,35 +61,80 @@ public ClusterConfig Config
         /// Recreates the DynamicState data.
         /// </summary>
         public void UpdateDynamicState()
+        {
+            UpdateDynamicStateInternal(force: false);
```
Comment (halter73) [inline src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:65]: So it's okay if this doesn't actually update _dynamicState? Why is that? Is there guaranteed to be calls to this method on a regular interval or every request or something like that? This should probably be renamed to something like TryUpdateDynamicState or MaybeUpdateDynamicState.

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs (hunk 21 above)
Comment (Tratcher) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:89]: SemaphoreSlim lets two threads in, not just one. That's how we ensure the current + 1 behavior we want.

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs (hunk 22 above)
Comment (Tratcher) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:65]: It's OK for this to exit early so long as another update is already queued ahead of it on the lock. So long as that update hasn't started yet, any additional requested update would be redundant.

**Comment by davidfowl** [comment]
This health check isn't on by default right? You have to turn on the policy?

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs (hunk 19 above)
Comment (alnikola) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:133]: Hmm, it happens to be `lock` can throw only in case of [obj being null](https://docs.microsoft.com/en-us/dotnet/api/system.threading.monitor.enter?view=net-5.0#System_Threading_Monitor_Enter_System_Object_System_Boolean__) which is not possible here. So, the outer try/finally is not necessary. I will remove it.

File: src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs (hunk 1 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs:61]: Done #538

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs (hunk 19 above)
Comment (alnikola) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs]: Outer try/finally removed, but the inner one it kept as is because the semaphore must be released while still holding the lock. I added a comment there explaining why it's important.

File: src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs (hunk 18 above)
Comment (alnikola) [reply src/ReverseProxy/Service/HealthChecks/IDestinationHealthUpdater.cs]: Task has been removed from the public API because I do agree it looked extremely confusing. For testing purposes, there is an internal `Task SetPassiveAsync` method has been added directly on the concrete `DestinationHealthUpdater` class.

**Comment by alnikola** [comment]
> This health check isn't on by default right? You have to turn on the policy?

@davidfowl That's correct. Health checks are disabled by default, they can be enabled in the configuration on per cluster basis as it's explained in the docs.

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs (hunk 22 above)
Comment (alnikola) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs:65]: I do agree we should somehow reflect on the name an eventual character of this method. But, we can do it as a small follow-up PR after a discussion.

File: src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs (hunk 21 above)
Comment (halter73) [reply src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs]: I didn't notice that this was releasing the semaphore before releasing the lock. Clever.
