### PR TITLE
Close WebSockets gracefully

### LINKED ISSUE #1770: WebSockets not closed gracefully
### Describe the bug
After the client and server have exchanged graceful WS Close messages, YARP isn't gracefully closing the connection. After a few seconds the client times out and closes the connection. This causes the client (E.g. Chrome) to report a WS error (1006) rather than a graceful close (1000).

### To Reproduce
1. Create a WebSocket connection through YARP
2. Close it gracefully from both sides
3. Observe a multi-second pause and then the client disconnects and may report an error

This reproduces with YARP running on Kestrel, HttpSys, and IIS Express. The client can be chrome, edge or even HttpClient, though that doesn't report an error.

It also reproduces in our WebSocket functional tests, causing them to take 1s or longer, vs a few ms when I tell YARP to cancel the request read.
https://github.com/microsoft/reverse-proxy/blob/b9f43dd4b383e7c2e1b222c0dd6587a848d88a56/test/ReverseProxy.FunctionalTests/WebSocketTests.cs#L26

I think the problem is here:
https://github.com/microsoft/reverse-proxy/blob/b9f43dd4b383e7c2e1b222c0dd6587a848d88a56/src/ReverseProxy/Forwarder/HttpForwarder.cs#L593

After the client and destination have exchanged close messages the destination closes the connection. YARP sees the response copy complete, but then waits for the request side to be closed from the client. Instead it should cancel the ongoing read.

### Further technical details
Version: 1.1
Reported by an internal partner

Recommend we patch this in 1.1

### PR DESCRIPTION
**Pull request by Tratcher**
Forward port of #1773 into main. Contributes to #1770.

TODO: I'm seeing some failures in WebSocketTelemetryTests that didn't show up in the original PR, but are now showing up locally in both 1.1 and main. 🤷 
- I partially understand now. Before a server graceful disconnect presented as a client timeout. Now YARP cancels the reads and suppresses the error, causing the telemetry to report Unknown.
- The telemetry can track reads and know when read returns 0, but it can't know when the write stream is closed unless it tries to write to it.

The test changes should be backported to 1.1.

### CODE REVIEW

File: test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs [hunk 1]
```diff
@@ -90,15 +90,15 @@ public enum Behavior
...
     [InlineData(Behavior.ClosesConnection, Behavior.SendsClose_ClosesConnection, WebSocketCloseReason.ServerGracefulClose, WebSocketCloseReason.ClientDisconnect)]
     [InlineData(Behavior.ClosesConnection, Behavior.SendsClose_WaitsForClose, WebSocketCloseReason.ServerGracefulClose, WebSocketCloseReason.ClientDisconnect)]
     // One side closes the connection while the other is waiting for messages
     [InlineData(Behavior.ClosesConnection, Behavior.WaitsForClose_SendsClose, WebSocketCloseReason.ClientDisconnect)]
     [InlineData(Behavior.ClosesConnection, Behavior.WaitsForClose_ClosesConnection, WebSocketCloseReason.ClientDisconnect)]
-    [InlineData(Behavior.WaitsForClose_SendsClose, Behavior.ClosesConnection, WebSocketCloseReason.ServerDisconnect)]
-    [InlineData(Behavior.WaitsForClose_ClosesConnection, Behavior.ClosesConnection, WebSocketCloseReason.ServerDisconnect)]
+    [InlineData(Behavior.WaitsForClose_SendsClose, Behavior.ClosesConnection, WebSocketCloseReason.ServerDisconnect, WebSocketCloseReason.Unknown)]
+    [InlineData(Behavior.WaitsForClose_ClosesConnection, Behavior.ClosesConnection, WebSocketCloseReason.ServerDisconnect, WebSocketCloseReason.Unknown)]
```
Comment (MihaZupan) [inline test/ReverseProxy.FunctionalTests/WebSocketsTelemetryTests.cs:101]: We should fix this case in `WebSocketsTelemetryStream` instead of changing the test.
These `Unknown` results should be `ServerDisconnect`s - this is an observable product bug in telemetry otherwise.

From offline discussion:

> Before if the destination disconnected while the client was still sending data (at least keep-alives), YARP would blow up when trying to write to the destination, and we would assign the blame to the destination.


> Now you have a race where if YARP is fast enough, it will set cancelReads = true and swallow the destination write failure exception. In this case the telemetry has no idea what's going on since neither side sent a WS close, and there is no forwarder error either.

> What may be happening in CI is that the machines are just slower so the write failure happens to be observed before we decide to cancel reads.


> We could change [this case of GetCloseReason](https://github.com/microsoft/reverse-proxy/blob/9d612d4c34f390a33bc5bdaa5ec1bac6f8251015/src/ReverseProxy/WebSocketsTelemetry/WebSocketsTelemetryStream.cs#L62-L64) to `ServerDisconnect` since it should really only be happening in this new situation where the server disconnected and we swallowed the error.

**Review by MihaZupan — APPROVED** [review]
