### PR TITLE
Remove connection-specific headeres for HTTP/2 and HTTP/3

### LINKED ISSUE #583: HTTP/2 connection to YARP with HTTP/1.1 to backend fails
### Describe the bug
I have set up a sample application with routing from https://localhost:5001 to a docker container that echoes all received headers. The container is running on http://localhost:8080. It responds with a connection=keep-alive, causing f.ex. curl to complain as this is not valid in the http/2 context.

```
* http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [connection], value: [keep-alive]
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Question:** Is this a supported scenario - i.e. going from a secured, HTTP/2 channel with a HTTP/1.1 backend? Is it the client  (which has no knowledge of this) or proxy that is responsible of adhering to the protocol change?

### To Reproduce
Run some image on a non-HTTPS binding. Example:
`docker run -p 8080:8080 brndnmtthws/nginx-echo-headers`

Run a simple YARP instance pointing all traffic to http://localhost:8080
`dotnet run ReverseProxySample`

From WSL or similar, do a curl
`curl --insecure -v https://localhost:5001`

### Further technical details

- Include the version of the packages you are using
`1.0.0-preview.7.*`

- The platform (Linux/macOS/Windows)
`Linux and Windows`

### PR DESCRIPTION
**Pull request by MihaZupan**
Fixes #583

YARP workaround for https://github.com/dotnet/aspnetcore/pull/24543 that was merged into 6.0 in Kestrel.

### CODE REVIEW

File: src/ReverseProxy/Utilities/RequestUtilities.cs [hunk 1]
```diff
@@ -14,11 +14,26 @@ namespace Microsoft.ReverseProxy.Utilities
...
     {
-        // TODO: this list only contains "Transfer-Encoding" because that messes up Kestrel. If we don't need to add any more here then it would be more efficient to
-        // check for the single value directly. What about connection headers?
-        internal static readonly HashSet<string> ResponseHeadersToSkip = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
+        internal static bool ShouldSkipResponseHeader(string headerName, bool isHttp2OrGreater)
         {
-            HeaderNames.TransferEncoding
+            if (isHttp2OrGreater)
+            {
+                // This check can be dropped in .NET 6.0+ as these headers will be removed by Kestrel
```
Comment (Tratcher) [inline src/ReverseProxy/Utilities/RequestUtilities.cs:21]: It's probably better to keep the check even after the kestrel fix. It should be more efficient to avoid adding the header than to add and remove it.

**Review by Tratcher — COMMENTED** [review]
This handles h2 response protocol correctness but there are more scenarios to consider. https://tools.ietf.org/html/rfc7230#section-6.1 says we should remove the Connection header from all requests and responses, and all headers referenced by that (e.g. forwarding `Connection: close` would be bad for proxy scenarios). However, removing `Connection: Upgrade` would break WebSockets.

**Comment by Tratcher** [comment]
We also need to test what happens for requests. Does HttpClient filter out these headers on h2/3?

**Comment by MihaZupan** [comment]
This PR specifically fixes the Http2 client => Http11 backend scenario described in #583.

Should the connection header (#439) be dealt-with in the same PR?

**Comment by Tratcher** [comment]
This PR should also cover the request version of the #583 scenario.

Do some reading about the Connection header and decide if you want to handle that at the same time or as a separate issue/PR.

**Comment by MihaZupan** [comment]
On the request side, HttpClient drops these headers:
https://github.com/dotnet/runtime/blob/45be6750943a043c15f2ce5e4700e48e63b5c7c0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1143

**Comment by Tratcher** [comment]
That's good. HttpClient doesn't skip the Keep-Alive header?

**Review by Tratcher — APPROVED** [review]
The Keep-Alive question can be investigated separately.
