### PR TITLE
Transforms in "Always" mode are run even if there is no response

### LINKED ISSUE #1056: No response transforms if the destination fails to respond
https://github.com/microsoft/reverse-proxy/issues/1051#issuecomment-854811689 (@brentnewbury-work)

### Describe the bug
Response transforms are skipped if the destination fails to respond due to a connection issue or timeout. A fixed status code is set and processing exits:
https://github.com/microsoft/reverse-proxy/blob/2fd46596c7cc370660f024e442ac3c8c00b88acf/src/ReverseProxy/Proxy/HttpProxy.cs#L134-L143
https://github.com/microsoft/reverse-proxy/blob/2fd46596c7cc370660f024e442ac3c8c00b88acf/src/ReverseProxy/Proxy/HttpProxy.cs#L460-L477

Some response transforms like ResponseHeader have the setting to run on "Success" or "Always", but always does not currently include the failure-to-respond scenario. It might even make sense to add a "Failure" mode to only run transforms for 5xx and connection failures. 

I'm mainly concerned about the "Always" case since people expect it run and generate consistent output. Failure cases can already be handled by the caller, but you don't want to duplicate logic for the Always scenario.

We would want to make the ProxyError value available to these transforms.

### PR DESCRIPTION
**Pull request by alnikola**
Fixes #1056

### CODE REVIEW

File: src/ReverseProxy/Forwarder/HttpForwarder.cs [hunk 1]
```diff
@@ -144,7 +144,7 @@ public HttpForwarder(ILogger<HttpForwarder> logger, IClock clock)
                 }
                 catch (Exception requestException)
```
Comment (Tratcher) [inline src/ReverseProxy/Forwarder/HttpForwarder.cs:145]: What about the OperationCanceledException code path?

File: src/ReverseProxy/Transforms/ResponseTrailersTransform.cs [hunk 2]
```diff
@@ -41,6 +41,12 @@ public static StringValues TakeHeader(ResponseTrailersTransformContext context,
             }
 
             var existingValues = StringValues.Empty;
+
+            if (context.ProxyResponse == null)
```
Comment (Tratcher) [inline src/ReverseProxy/Transforms/ResponseTrailersTransform.cs:45]: Debug.Assert.

File: src/ReverseProxy/Transforms/ResponseTransform.cs [hunk 3]
```diff
@@ -39,6 +39,12 @@ public static StringValues TakeHeader(ResponseTransformContext context, string h
             }
 
             var existingValues = StringValues.Empty;
+
+            if (context.ProxyResponse == null)
```
Comment (Tratcher) [inline src/ReverseProxy/Transforms/ResponseTransform.cs:43]: This check could be delayed until the `else if` block. We want to avoid making assumptions about the HttpContext content.

File: src/ReverseProxy/Transforms/ResponseHeaderRemoveTransform.cs [hunk 4]
```diff
@@ -35,7 +35,7 @@ public override ValueTask ApplyAsync(ResponseTransformContext context)
                 throw new ArgumentNullException(nameof(context));
             }
 
-            if (Always || Success(context))
+            if (context.ProxyResponse != null && (Always || Success(context)))
```
Comment (Tratcher) [inline src/ReverseProxy/Transforms/ResponseHeaderRemoveTransform.cs:38]: This check isn't necessary, ProxyResponse isn't accessed on this code path.

File: src/ReverseProxy/Transforms/ResponseTrailersAllowedTransform.cs [hunk 5]
```diff
@@ -41,6 +41,11 @@ public override ValueTask ApplyAsync(ResponseTrailersTransformContext context)
                 throw new ArgumentNullException(nameof(context));
             }
 
+            if (context.ProxyResponse == null)
```
[the remark this answers is not in the document]
Comment (alnikola) [reply src/ReverseProxy/Transforms/ResponseTrailersAllowedTransform.cs]: Replaced all null checks with Debug.Assert in the response trailers transforms. The relevant tests are also removed since we don't expect this code to be called when context.ProxyResponse is null.

File: src/ReverseProxy/Transforms/ResponseHeaderRemoveTransform.cs (hunk 4 above)
Comment (alnikola) [reply src/ReverseProxy/Transforms/ResponseHeaderRemoveTransform.cs]: Fixed

File: src/ReverseProxy/Transforms/ResponseTransform.cs (hunk 3 above)
Comment (alnikola) [reply src/ReverseProxy/Transforms/ResponseTransform.cs]: Fixed

File: src/ReverseProxy/Forwarder/HttpForwarder.cs (hunk 1 above)
Comment (alnikola) [reply src/ReverseProxy/Forwarder/HttpForwarder.cs:152]: Added call to the response transformer there too.

File: test/ReverseProxy.Tests/Transforms/ResponseHeaderValueTransformTests.cs [hunk 6]
```diff
@@ -12,35 +12,38 @@ public class ResponseHeaderValueTransformTests
...
+        [InlineData("start", 200, "new", true, true, "start;new", false)]
+        [InlineData("start,value", 400, "new", true, false, "start,value", false)]
+        [InlineData("start,value", 200, "new", true, false, "start,value;new", false)]
+        [InlineData("start,value", 400, "new", true, true, "start,value;new", false)]
+        [InlineData("start,value", 200, "new", true, true, "start,value;new", false)]
+        [InlineData("start;value", 400, "new", true, false, "start;value", false)]
+        [InlineData("start;value", 200, "new", true, false, "start;value;new", false)]
+        [InlineData("start;value", 400, "new", true, true, "start;value;new", false)]
+        [InlineData("start;value", 200, "new", true, true, "start;value;new", false)]
+        public async Task AddResponseHeader_Success(string startValue, int status, string value, bool append, bool always, string expected, bool responseNull)
```
Comment (MihaZupan) [inline test/ReverseProxy.Tests/Transforms/ResponseHeaderValueTransformTests.cs:38]:
```suggestion
        public async Task AddResponseHeader_Success(string startValue, int status, string value, bool append, bool always, string expected, bool responseNull = false)
```
Nit: May be more readable since only a handful of cases set it.

**Review by MihaZupan — APPROVED** [review]
