### PR TITLE
Fix race conditions in EntityActionScheduler

### LINKED ISSUE #1136: Fix race conditions in EntityActionScheduler
The main issue is in `ScheduleEntity` where it will register the timer (autostart) before adding it to the dictionary.

A few scenarios:

1.
- Thread A calls ScheduleEntity and autostart is false
- Thread B calls Start, switching autostart to true
- Thread B enumerates the dictionary and enables all timers
- Thread A adds the unscheduled entry to the dictionary, where it will live forever taking up memory and never firing

2.
- Thread A calls ScheduleEntity and autostart is true
- The timer we just created fires and the callback is invoked
- Thread B executes the timer callback
- Thread A adds the entry into the dictionary
- Since the timer callback never saw the entry in the dictionary, it will never remove it from it. Any timer that isn't "runOnce" will never be re-scheduled.

### PR DESCRIPTION
**Pull request by alnikola**
Fixes #1136

### CODE REVIEW

File: src/ReverseProxy/Health/EntityActionScheduler.cs [hunk 1]
```diff
@@ -56,14 +56,23 @@ public void Start()
...
             {
-                entry.Timer.Change(entry.Period, Timeout.Infinite);
+                entry.SetTimer();
             }
         }
 
         public void ScheduleEntity(T entity, TimeSpan period)
         {
-            var entry = new SchedulerEntry(entity, (long)period.TotalMilliseconds, _timerCallback, Volatile.Read(ref _isStarted) == 1, _timerFactory);
+            var isStarted = Volatile.Read(ref _isStarted);
```
Comment (gfoidl) [inline src/ReverseProxy/Health/EntityActionScheduler.cs:65]: I think this read here can be omitted, as `isStarted` isn't used up until L71 which could be written as
```c#
if (Volatile.Read(ref _isStarted) == 1)
{
    entry.SetTimer();
}
```
So no matter what state `_isStarted` has, there's only one volatile read. And that read is the right place to get the freshest value (due to the memory barriers from Interlocked.Exchange).

Comment (alnikola) [reply src/ReverseProxy/Health/EntityActionScheduler.cs]: Oh, you are right. Thanks for finding that. Fixed.

**Review by MihaZupan — APPROVED** [review]
